### ISSUE TITLE
test.py does not work

### ISSUE THREAD

**Issue by zajer** [calebh/dihash#1]
I've tried to run test.py with nauty 2.7 and pynauty 0.6 and got the following error:
```
Traceback (most recent call last):
  File "test.py", line 26, in <module>
    hash_graph(g, collapse_orbits=True)
  File "/home/pc/Desktop/Python3_Projects/dihash/dihash.py", line 131, in hash_graph
    hash_scc(g, cond, r, collapse_orbits=collapse_orbits)
  File "/home/pc/Desktop/Python3_Projects/dihash/dihash.py", line 85, in hash_scc
    hash_scc(g, cond, succ, collapse_orbits=collapse_orbits)
  File "/home/pc/Desktop/Python3_Projects/dihash/dihash.py", line 97, in hash_scc
    canonization = canonize(scc_graph)
  File "/home/pc/Desktop/Python3_Projects/dihash/dihash.py", line 25, in canonize
    canon = pynauty.canon_label(nauty_g)
AttributeError: module 'pynauty' has no attribute 'canon_label'
```
I am using python 3.7.5

**Comment by zajer** [comment]
Ok so the reason I've got the above error is because I used official version of pynauty from here:
https://web.cs.dal.ca/~peter/software/pynauty/html/index.html
If I switch to version 1.0 from here:
https://github.com/sammorley-short/pynauty
Everything seems to work fine.

**Comment by calebh** [comment]
This is correct. I will add this as a note in the readme.
